apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ojhv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ojhv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ojhv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ojhv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ojhv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-omin-tenant/rhtap-demo-app/hacbs-test-project-ojhv@sha256:6edf7defbc97d465c74e28582fd3e0e94478f08e4ab38315abab94cbd50e6bd4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
