apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ojhv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-omin-tenant/rhtap-demo-app/hacbs-test-project-ojhv@sha256:f85cd1b07ab532fd418c26dcb2d3795b0cd8f19463131c02dd1124b94a697103
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
